try:
    print(2/1)
except Exception as e:
    print(e)
finally:
    print("Je ne peut pas")
